version: '3'

services:
    rabbitmq:
        image: rabbitmq:3.8-management
        ports: ['5671:5671', '15671:15671']
        environment:
            - RABBITMQ_SECURE_PASSWORD=yes
            - RABBITMQ_SSL_CACERTFILE=/rabbitmq-certs/cert.pem
            - RABBITMQ_SSL_CERTFILE=/rabbitmq-certs/cert.pem
            - RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT=false
            - RABBITMQ_SSL_KEYFILE=/rabbitmq-certs/unenc.pem
            - RABBITMQ_SSL_VERIFY=verify_none
        volumes:
            - 'rabbitmq_data:/var/lib/rabbitmq'
            - '.ops/certs:/rabbitmq-certs'

    haproxy:
        image: haproxy:2.4
        ports: ['25671:25671', '8404:8404']
        environment:
            - HAPROXY_RABBITMQ_HOST=${HAPROXY_RABBITMQ_HOST}
        volumes:
            - '.ops/haproxy.conf:/usr/local/etc/haproxy/haproxy.cfg'

volumes:
    rabbitmq_data:
        driver: local
